name: glimpse_imputation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - _r-mutex=1.0.1
  - alsa-lib=1.2.8
  - angsd=0.940
  - annotated-types=0.7.0
  - attrs=26.1.0
  - backports.zstd=1.5.0
  - bcftools=1.23.1
  - beagle=5.5_27Feb25.75f
  - binutils_impl_linux-64=2.45.1
  - binutils_linux-64=2.45.1
  - blas=2.307
  - blas-devel=3.11.0
  - boltons=25.0.0
  - boost=1.80.0
  - boost-cpp=1.80.0
  - bowtie2=2.5.5
  - brotli-python=1.2.0
  - brotlicffi=1.2.0.1
  - bwa-mem2=2.3
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.6.17
  - cairo=1.16.0
  - certifi=2026.6.17
  - cffi=2.0.0
  - charset-normalizer=3.4.7
  - choreographer=1.3.0
  - click=8.4.0
  - coloredlogs=15.0.1
  - colormath=3.0.0
  - conda=23.7.4
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cpp-expected=1.3.1
  - cpython=3.11.15
  - cryptography=48.0.0
  - curl=8.19.0
  - damageprofiler=1.1
  - expat=2.8.1
  - fastp=1.3.3
  - fastqc=0.12.1
  - fmt=10.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.18.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.3
  - fribidi=1.0.16
  - gatk4=4.6.2.0
  - gcc_impl_linux-64=15.2.0
  - gcc_linux-64=15.2.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gfortran_impl_linux-64=15.2.0
  - gfortran_linux-64=15.2.0
  - giflib=5.2.2
  - glib=2.78.1
  - glib-tools=2.78.1
  - glimpse-bio=2.0.1
  - graphite2=1.3.14
  - gsl=2.7
  - gxx_impl_linux-64=15.2.0
  - gxx_linux-64=15.2.0
  - h2=4.3.0
  - harfbuzz=6.0.0
  - hpack=4.1.0
  - htslib=1.23.1
  - humanfriendly=10.0
  - humanize=4.15.0
  - hyperframe=6.1.0
  - icu=70.1
  - idna=3.15
  - importlib-metadata=8.8.0
  - isa-l=2.31.1
  - jinja2=3.1.6
  - jpeg=9f
  - jsonpatch=1.33
  - jsonpointer=3.1.1
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - kaleido-core=0.2.1
  - kernel-headers_linux-64=6.12.0
  - keyutils=1.6.3
  - king=2.3.2
  - krb5=1.20.1
  - lcms2=2.15
  - ld_impl_linux-64=2.45.1
  - lerc=4.1.0
  - libarchive=3.6.2
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcups=2.3.3
  - libcurl=8.19.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.8.1
  - libffi=3.5.2
  - libfreetype=2.14.3
  - libfreetype6=2.14.3
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.78.1
  - libgomp=15.2.0
  - libhwy=1.3.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libkrb5=1.22.1
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - liblzma=5.8.3
  - liblzma-devel=5.8.3
  - libmamba=1.5.1
  - libmambapy=1.5.1
  - libnghttp2=1.67.1
  - libnsl=2.0.1
  - libopenblas=0.3.33
  - libpng=1.6.58
  - libsanitizer=15.2.0
  - libsolv=0.7.37
  - libsqlite=3.53.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.42.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.10.3
  - libzlib=1.3.2
  - lmdb=0.9.35
  - logistro=2.0.1
  - lz4-c=1.9.4
  - lzo=2.10
  - make=4.4.1
  - mamba=1.5.1
  - markdown=3.10.2
  - markdown-it-py=4.2.0
  - markupsafe=3.0.3
  - mathjax=2.7.7
  - mdurl=0.1.2
  - mosdepth=0.3.14
  - multiqc=1.35
  - narwhals=2.21.2
  - natsort=8.4.0
  - ncurses=6.6
  - networkx=3.6.1
  - nlohmann_json=3.12.0
  - nspr=4.38
  - nss=3.118
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.33
  - openjdk=17.0.3
  - openjpeg=2.5.0
  - openssl=3.6.3
  - orjson=3.11.9
  - packaging=26.2
  - pango=1.50.14
  - pcre2=10.40
  - perl=5.32.1
  - picard=3.4.0
  - pigz=2.8
  - pillow=11.0.0
  - pip=26.1.1
  - pixman=0.46.4
  - platformdirs=4.9.6
  - plink=1.90b7.7
  - plink2=2.0.0a.6.9
  - plotly=6.6.0
  - pluggy=1.6.0
  - polars=1.40.1
  - polars-runtime-32=1.40.1
  - polars-runtime-compat=1.40.1
  - pthread-stubs=0.4
  - pyaml-env=1.2.2
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=3.0
  - pydantic=2.13.4
  - pydantic-core=2.46.4
  - pygments=2.20.0
  - pyopenssl=26.2.0
  - pysocks=1.7.1
  - python=3.11.15
  - python-dotenv=1.2.2
  - python-gil=3.11.15
  - python-kaleido=0.2.1
  - python_abi=3.11
  - pyyaml=6.0.3
  - r-base=4.2.3
  - readline=8.3
  - referencing=0.37.0
  - regex=2026.5.9
  - reproc=14.2.7.post0
  - reproc-cpp=14.2.7.post0
  - requests=2.34.2
  - rich=15.0.0
  - rich-click=1.9.7
  - rpds-py=0.30.0
  - ruamel.yaml=0.17.40
  - ruamel.yaml.clib=0.2.15
  - ruamel_yaml=0.15.80
  - samtools=1.23.1
  - sed=4.10
  - setuptools=82.0.1
  - simdjson=4.6.4
  - simplejson=4.1.1
  - spdlog=1.14.1
  - spectra=0.0.11
  - sqlite=3.53.1
  - sysroot_linux-64=2.39
  - tiktoken=0.12.0
  - tk=8.6.13
  - tktable=2.10
  - toolz=1.1.0
  - tqdm=4.67.3
  - trimmomatic=0.40
  - typeguard=4.5.2
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.7.0
  - vcftools=0.1.17
  - verifybamid2=2.0.3
  - wheel=0.47.0
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.13
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.3
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-xorgproto=2025.1
  - xz=5.8.3
  - xz-gpl-tools=5.8.3
  - xz-tools=5.8.3
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zipp=4.1.0
  - zlib=1.3.2
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - bx-python==0.14.0
      - crossmap==0.7.3
      - pandas==3.0.3
      - pybigwig==0.3.25
      - pyparsing==3.3.2
      - pysam==0.24.0
      - python-dateutil==2.9.0.post0
      - six==1.17.0
